# Generated by Django 4.0.3 on 2022-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snapshot',
            field=models.ImageField(default='default.jpg', upload_to='snapshots_images'),
        ),
    ]
