# Generated by Django 4.0.3 on 2022-04-10 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0002_project_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='snapshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='snapshots_images'),
        ),
    ]
